import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import SessionProviderClientComponent from "./_components/auth/session-client-provider";
import AppContextProvider from "./_components/global/context";

export const metadata: Metadata = {
  title: "47Labs - Dev Setup",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} antialiased h-full`}>
      <body className="min-h-screen h-full p-2 lg:p-4">
        <SessionProviderClientComponent>
          <AppContextProvider>
            <TRPCReactProvider>
              {children}
            </TRPCReactProvider>
          </AppContextProvider>
        </SessionProviderClientComponent>
      </body>
    </html>
  );
}
